### PR TITLE
Update Sonarr parsing && reformat

### PR DESCRIPTION
**Pull request by supersnellehenk**
Fix Sonarr V4 and improve filename matching to IMDB

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
@supersnellehenk should we keep this backwards compatible so you can set it to v3 if needed?

**Comment by supersnellehenk** [comment]
> @supersnellehenk should we keep this backwards compatible so you can set it to v3 if needed?

Good point, please keep this open until I've tested with V3. I assumed their V3 api is in Sonarr V3 as well, but I'm not sure.

**Comment by supersnellehenk** [comment]
> I can confirm the API call works in Sonarr v3 and returns the expected series.
> 
> 

Thanks for testing, haven't had the time to setup a V3 instance myself. So @HaveAGitGat if the code checks out fine it can be merged.

**Comment by HaveAGitGat** [comment]
Thanks guys, will merge

**Pull request merged**
