### PR TITLE
Fixed NaN Issue For Bitrates And findMediaInfoItem for Subtitles

### PR DESCRIPTION
**Pull request by zachg99**
Fixed the NaN issue with BitRates. 

Some files had bitrate missing in the MediaInfo data so pulling from the "extra" section for those. 

Also resolved an issue with the way the findMediaInfoItem function wasn't working with subtitle tracks (well it wasn't working for all files due to the general section because of a previous attempted subtitle fix but this should be much much much better and work in most all cases).

### CODE REVIEW

**Comment by supersnellehenk** [comment]
A bunch of stuff has been removed like ```const loadDefaultValues = require('../methods/loadDefaultValues');```, could you pull the latest version of the plugin and edit that one instead?

**Comment by zachg99** [comment]
Will do!

--
Our problems are like diamonds. We inflate their value because we don't understand how many they have in Africa.

**Comment by zachg99** [comment]
Updated version committed and pushed.

**Review by HaveAGitGat — APPROVED** [review]

**Comment by supersnellehenk** [comment]
@HaveAGitGat es-lint is still disabled for this plugin, should we enable it?

**Comment by zachg99** [comment]
I'm ok with doing that, however I seem to remember when i went to check a change in sometime back I received a bunch of formatting errors. Then i noticed the community version had eslint disabled so went with that and it was fine.

Is there an eslint guide or formatter script i can use to clean up the plugin to conform to the projects requirements?

**Comment by HaveAGitGat** [comment]
I've fixed 50 or so of the lint errors (mostly lines being too long).

There are these ones remaining:

```
 248:9   error  'bolIncludeSubs' is assigned a value but never used              no-unused-vars
  251:16  error  Unexpected require()                                             global-require
  294:22  error  Expected '===' and instead saw '=='                              eqeqeq
  295:35  error  Expected '!==' and instead saw '!='                              eqeqeq
  296:52  error  Expected '!==' and instead saw '!='                              eqeqeq
  297:52  error  Expected '===' and instead saw '=='                              eqeqeq
  306:22  error  Expected '===' and instead saw '=='                              eqeqeq
  309:40  error  Expected '!==' and instead saw '!='                              eqeqeq
  310:79  error  Expected '!==' and instead saw '!='                              eqeqeq
  315:39  error  Expected '!==' and instead saw '!='                              eqeqeq
  315:96  error  Expected '!==' and instead saw '!='                              eqeqeq
  335:9   error  'output' is not defined                                          no-undef
  341:1   error  This line has a length of 170. Maximum allowed is 120            max-len
  349:9   error  'optimalbitrate' is assigned a value but never used              no-unused-vars
  383:23  error  Expected '===' and instead saw '=='                              eqeqeq
  385:7   error  All 'var' declarations must be at the top of the function scope  vars-on-top
  385:7   error  Unexpected var, use let or const instead                         no-var
  385:19  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  404:27  error  Expected '===' and instead saw '=='                              eqeqeq
  408:22  error  Expected '===' and instead saw '=='                              eqeqeq
  411:26  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  412:17  error  'curstreamheight' is assigned a value but never used             no-unused-vars
  414:17  error  'curstreamFPS' is assigned a value but never used                no-unused-vars
  432:23  error  Expected '===' and instead saw '=='                              eqeqeq
  440:43  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  443:45  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  447:42  error  Expected '!==' and instead saw '!='                              eqeqeq
  448:54  error  Expected '===' and instead saw '=='                              eqeqeq
  454:22  error  Expected '===' and instead saw '=='                              eqeqeq
  459:50  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  464:36  error  Expected '===' and instead saw '=='                              eqeqeq
  473:27  error  Expected '===' and instead saw '=='                              eqeqeq
  478:50  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  483:36  error  Expected '===' and instead saw '=='                              eqeqeq
  494:57  error  Expected '===' and instead saw '=='                              eqeqeq
  494:84  error  Expected '===' and instead saw '=='                              eqeqeq
  496:32  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  496:68  error  Expected '!==' and instead saw '!='                              eqeqeq
  498:52  error  Expected '===' and instead saw '=='                              eqeqeq
  538:16  error  Expected '===' and instead saw '=='                              eqeqeq
  545:3   error  All 'var' declarations must be at the top of the function scope  vars-on-top
  545:3   error  Unexpected var, use let or const instead                         no-var
  545:7   error  'MILoc' is already defined                                       no-redeclare
  545:7   error  'MILoc' used outside of binding context                          block-scoped-var
  545:15  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  549:39  error  'MILoc' used outside of binding context                          block-scoped-var
  550:38  error  'MILoc' used outside of binding context                          block-scoped-var
  553:36  error  'MILoc' used outside of binding context                          block-scoped-var
  557:48  error  Expected '!==' and instead saw '!='                              eqeqeq
  558:60  error  Expected '!==' and instead saw '!='                              eqeqeq
  564:28  error  'MILoc' used outside of binding context                          block-scoped-var
  564:50  error  Expected '===' and instead saw '=='                              eqeqeq
  581:3   error  'optimalvideobitrate' is not defined                             no-undef
  582:86  error  'optimalvideobitrate' is not defined                             no-undef
  585:56  error  'optimalvideobitrate' is not defined                             no-undef
  587:46  error  'optimalvideobitrate' is not defined                             no-undef
  588:5   error  'optimalvideobitrate' is not defined                             no-undef
  589:63  error  'optimalvideobitrate' is not defined                             no-undef
  591:46  error  'optimalvideobitrate' is not defined                             no-undef
  592:5   error  'optimalvideobitrate' is not defined                             no-undef
  593:63  error  'optimalvideobitrate' is not defined                             no-undef
  595:46  error  'optimalvideobitrate' is not defined                             no-undef
  596:5   error  'optimalvideobitrate' is not defined                             no-undef
  597:14  error  'optimalvideobitrate' is not defined                             no-undef
  599:46  error  'optimalvideobitrate' is not defined                             no-undef
  600:5   error  'optimalvideobitrate' is not defined                             no-undef
  604:53  error  Expected '!==' and instead saw '!='                              eqeqeq
  609:55  error  Expected '===' and instead saw '=='                              eqeqeq
  615:53  error  Expected '===' and instead saw '=='                              eqeqeq
  626:18  error  'optimalvideobitrate' is not defined                             no-undef
  629:55  error  Expected '===' and instead saw '=='                              eqeqeq
  630:26  error  Expected '===' and instead saw '=='                              eqeqeq
  632:1   error  This line has a length of 126. Maximum allowed is 120            max-len
  632:79  error  'optimalvideobitrate' is not defined                             no-undef
  637:9   error  'optimalvideobitrate' is not defined                             no-undef
  643:13  error  'optimalvideobitrate' is not defined                             no-undef
  645:7   error  'optimalvideobitrate' is not defined                             no-undef
  652:11  error  'optimalvideobitrate' is not defined                             no-undef
  654:87  error  'optimalvideobitrate' is not defined                             no-undef
  659:16  error  Expected '===' and instead saw '=='                              eqeqeq
  660:23  error  Expected '!==' and instead saw '!='                              eqeqeq
  670:38  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  673:36  error  'findMediaInfoItem' was used before it was defined               no-use-before-define
  695:53  error  Expected '!==' and instead saw '!='                              eqeqeq
  707:55  error  Expected '!==' and instead saw '!='                              eqeqeq
  810:57  error  'optimalvideobitrate' is not defined                             no-undef
  859:92  error  Expected '!==' and instead saw '!='                              eqeqeq
  861:30  error  Expected '===' and instead saw '=='                              eqeqeq
  861:57  error  Expected '===' and instead saw '=='                              eqeqeq
  867:21  error  Expected '===' and instead saw '=='                              eqeqeq
  867:45  error  Expected '===' and instead saw '=='                              eqeqeq
```

To run the lint check make sure you have `nodejs 14+` and `npm installed` and then in the plugins repo run

```
// install deps
npm i

// lint and auto fix errors which are auto-fixable.
npm run lint:fix
```

**Comment by HaveAGitGat** [comment]
Be careful with the `eqeqeq` errors.

**Comment by zachg99** [comment]
Thank you for the help and info.

I was able to fix all the eslint errors and still have a working plugin (at least from my testing). I wasn't able to get the key function that matches mediainfo tracks to ffprobe streams to work with === or !=== so after changing the rest of the comparisons over I switched that from an error to a warning.

**Comment by HaveAGitGat** [comment]
Made some general plugin changes so rebased onto master.

I've fixed the lint warnings, does it now work as intended? Should just be able to use 
`if (file.mediaInfo.track[i].StreamOrder) {`

Also fixed this ```currMIOrder == `0-${index}``` as no evaluation would be done. It would just end up as a string such as `0-1` or `0-1`. Unless that was intended?

**Comment by zachg99** [comment]
Ahh, I like that check better than the old  double != check, thank you.

So, StreamOrder in some video files is represented as a number (0, 1, 2, ...), other video files (like ts, and i think mp4) use a string (0-1, 0-2, 0-3, ....).  [It's described here.](https://sourceforge.net/p/mediainfo/discussion/297609/thread/c791c334/)

> In MediaInfo, I provide a "StreamOrder" field (hidden by default, in GUI you can see it in text mode + menuu debig->advanced), e.g. for TS this field is the PMT order in the PAT + dash + stream order in the PMT.

So the statement checking what is in currMIOrder is trying to take both formats into account, if it matches either then return the index. Also subtitles don't have a streamorder, from what i can tell anyway, so I'm getting the ID -1 value as the ID starts at 1 while the index of the track starts at 0.

**Comment by HaveAGitGat** [comment]
Think I might have rebased and added the changes at the same time you were doing some stuff. It should now be working as I re-added 
```
if (currMIOrder === index || currMIOrder === `0-${index}`) {
```

**Comment by zachg99** [comment]
So, I think because the index is an integer and currMIOrder the first check is failing. When i modify that line to be:

`if (currMIOrder == index || currMIOrder === `0-${index}`)`

It works, however if the first comparison has the === it fails.

**Comment by HaveAGitGat** [comment]
Ah I see, converted them both to integers just to be sure, so should now be working.

**Review by HaveAGitGat — APPROVED** [review]

**Review by supersnellehenk — APPROVED** [review]
Variable names should be lowerCamelCase though. Now it's all over the place.

**Comment by zachg99** [comment]
Understood. I have a few files that are giving me trouble and i need to sort that out, so i'll clean up the lowerCamelCase at the same time.

**Pull request merged**
