### PR TITLE
Add Tdarr_Plugin_drdd_standardise_all_in_one

### PR DESCRIPTION
**Pull request by dambler**
New plugin that does a bunch of things in a single pass rather than multiple (as would be required using mutliple plugins).

- Converts video to h265 where possible (there is a bitrate cut off).
- Ensures in MKV.
- Removes unwanted subtitle languages and commentary subtitles.
- Ensures multi channel audio is AC3 encoded.
- Removes commentary audio tracks.
- Supports both Intel Quick Sync and Nvidia NVENC encoding.

Edit: Should really say, a lot of the grunt work for this plugin was done by Migz - I used a lot of his logic and ideas!

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
TY

**Comment by josh-gaby** [comment]
@dambler the last update to this was called "QSV Mpeg4 fix" but it also forces mpeg4 files to be software encoded when using NVENC, was that done intentionally due to some known issue or should it be safe to re-enable HW transcoding for mpeg4 if using NVENC?

**Comment by milindpatel63** [comment]
@dambler @josh-gaby I too have similar question....my mpeg4 videos are not using gpu for transcoding....can we remove that "if statement" and re-enable hw transcoding for mpeg4?
i checked my gpu supported codecs using "ffmpeg -codecs", and it shows mpeg4_cuvid is supported...

**Comment by milindpatel63** [comment]
@josh-gaby thankss...will do the same...
I'll just remove this or statement..
if (
        (inputs.qsv !== "true" && inputs.nvenc !== "true") _**||
        stream.codec_name === "mpeg4"**_
      ) 

and i'll add another line..
else if (file.video_codec_name == "mpeg4") {
            configuration.AddInputSetting("-c:v mpeg4_cuvid");
          }

Is this correct?
Thanks for the quick reply though :D

**Comment by josh-gaby** [comment]
I changed the if statement as follows:
```
if (
        (inputs.qsv !== "true" && inputs.nvenc !== "true") ||
        stream.codec_name === "mpeg4"
) {
```
becomes
```
if (
        (inputs.qsv !== "true" && inputs.nvenc !== "true") || 
        (inputs.qsv == "true" && stream.codec_name === "mpeg4")
) {
```

that way the QSV/mpeg4 fix remains in place.

**Comment by milindpatel63** [comment]
@josh-gaby okk...thanks a lot (Y)

**Comment by dambler** [comment]
Nice one!

**Pull request merged**
