### PR TITLE
Add VP9 Plugin

### PR DESCRIPTION
**Pull request by ZachMyers3**
This plugin is for transcoding a video in VP9 video codec, Opus audio codec, and webvtt subtitle codec.

It allows allows for variable entry of quality by the given video quality and the option of removing different language and commentary audio and subtitle channels.

Related to #142.

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
New plugins shouldn’t have eslint disabled at the top, it helps keep the repo tidy and catches bugs 😁.

**Comment by ZachMyers3** [comment]
@HaveAGitGat I have removed eslint at the top and after working through my movie queue worked out any bugs that I have ran in to. Let me know if you want/need any further changes and I'll be happy to comply.

**Comment by supersnellehenk** [comment]
> @HaveAGitGat I have removed eslint at the top and after working through my movie queue worked out any bugs that I have ran in to. Let me know if you want/need any further changes and I'll be happy to comply.

Not sure if you can see the checks, but there's a few errors in there https://github.com/HaveAGitGat/Tdarr_Plugins/pull/154/checks which require solving before being able to be merged.

**Comment by ZachMyers3** [comment]
Should be resolved. Added `/* eslint max-classes-per-file: ["error", 2] */` on the top, as I don't believe I can separate these classes into other files and have the plugin work.

**Review by supersnellehenk — APPROVED** [review]

**Review by vodkapmp — APPROVED** [review]

**Pull request merged**
