### PR TITLE
Add config option for audio transcode bitrate

### PR DESCRIPTION
**Pull request by tmchow**
Give option to specify the bitrate of the transcoded audio

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
Hi thanks for the contribution.

The reason I haven't merged this is because, for people already using this plugin, all new files will be moved into the transcode error/cancelled tab due to no bitrate being entered (Tdarr pulls community plugin updates hourly). When modifying existing plugins it's best to do it in such a way that existing users won't be affected 👍.

**Comment by tmchow** [comment]
@HaveAGitGat good call. Let me refactor it a bit to make it optional.

**Comment by tmchow** [comment]
@HaveAGitGat Just adjusted to skip it if not provided.

**Comment by HaveAGitGat** [comment]
Thanks :)

**Pull request merged**
