### PR TITLE
Music library plugin, Audio to FLAC

### PR DESCRIPTION
**Pull request by aunefyren**
Made a plugin that converts from Apples ALAC codec to FLAC, losslessly. I use this myself and figured someone else might use it because there are no music library plugins.

### CODE REVIEW

**Comment by supersnellehenk** [comment]
@aunefyren Could you commit https://0bin.net/paste/cxJvy2hP#TjGuNTSrjjnSJ7EXHFH80Zo6joMdVG-2wh+AXmjb0pA instead, please? I rewrote it so it's a little cleaner plus it'll get past ESLint now.

**Comment by aunefyren** [comment]
> @aunefyren Could you commit https://0bin.net/paste/cxJvy2hP#TjGuNTSrjjnSJ7EXHFH80Zo6joMdVG-2wh+AXmjb0pA instead, please? Your branch is protected so I couldn't. I rewrote it so it's a little cleaner plus it'll get past ESLint now.

Thank you, well done! Noticed your code didn't check the frame rate, like my earlier version. Any reason for that? My version is quite old, but if I remember correctly I couldn't trust the video tag.

**Comment by supersnellehenk** [comment]
> Noticed your code didn't check the frame rate, like my earlier version. Any reason for that? My version is quite old, but if I remember correctly I couldn't trust the video tag.

Now you say it, ALAC can have posters in the file, correct? That's why you were checking the frame rate. Would have to put that back in, can be done by simply doing `&& x.avg_frame_rate !== "0/0"`.

**Comment by aunefyren** [comment]
> > Noticed your code didn't check the frame rate, like my earlier version. Any reason for that? My version is quite old, but if I remember correctly I couldn't trust the video tag.
> 
> Now you say it, ALAC can have posters in the file, correct? That's why you were checking the frame rate. Would have to put that back in, can be done by simply doing `&& x.avg_frame_rate !== "0/0"`.

Yeah, been a while, but I think that's what I figured out. Readded now 👍

**Review by aunefyren — COMMENTED** [review]
Looks great, good reformatting!

**Comment by HaveAGitGat** [comment]
@aunefyren would you mind just checking the tests are as you expect, thanks:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/4d06a170a614773c7e40aa247477aadf6700a5fe/tests/Community/Tdarr_Plugin_f4k1_aune_audio_to_flac.js

**Comment by aunefyren** [comment]
> @aunefyren would you mind just checking the tests are as you expect, thanks: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/4d06a170a614773c7e40aa247477aadf6700a5fe/tests/Community/Tdarr_Plugin_f4k1_aune_audio_to_flac.js

Yes, everything looks in order 👍

**Pull request merged**
