### PR TITLE
Add boosh changes

### PR DESCRIPTION
**Pull request by HaveAGitGat**

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
Ref: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/359

**Comment by HaveAGitGat** [comment]
@Boosh1 I've updated the tests, can you check if they're as expected ty

**Comment by Boosh1** [comment]
Sorry for delay. Tests seem fine to me, but do say if we we'd prefer to expand them to cover more option variations etc. Unsure how in depth tests should be.

**Comment by HaveAGitGat** [comment]
Looks fine, I normally just add a test for default inputs and then a couple or so for checking the various plugin inputs are working

**Pull request merged**
